version: 2
jobs:
  build:
    working_directory: ~/bostonhacks-squadra
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout

      - run:
          name: Bundle Install
          command: bundle check || bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: rails-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      - run:
          name: Validate team.yml
          command: bundle exec ruby validate.rb

  deploy:
      docker:
        - image: circleci/ruby:2.4-node
      steps:
          - run:
              name: Update bostonhacks team
              command: bundle exec ruby squadra.rb

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master