version: 2
jobs:
  build:
    working_directory: ~/bostonhacks-squadra
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout

      - restore_cache:
          keys:
            - rails-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --path vendor/bundle

      - save_cache:
          key: rails-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      - run:
          name: Validate team.yml
          command: bundle exec ruby validate.rb

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bundle exec ruby squadra.rb
            fi
